### ISSUE TITLE
Could not load data for tpcds, scale factor 10, using the schema sdb_all_tables_partition

### ISSUE THREAD

**Issue by sagathos** [swarm64/s64da-benchmark-toolkit#31]
Branch: master
git commit: 0c089b5b330c01d247b678da20bf6d000b88f249

spiros@smc-02:~/s64-benchmark-toolkit-git/s64da-benchmark-toolkit/schemas/tpcds [master]$ ./loader.sh --schema=sdb_all_tables_partition --scale-factor=10 --dbname=example3
Preparing DB
Deleting example3
Creating example3
Loading pre-schema
Loading schema
Traceback (most recent call last):
  File "prepare_benchmark", line 84, in <module>
    prepare.PrepareBenchmark(args, benchmark).run()
  File "/home/nethomes/spiros/s64-benchmark-toolkit-git/s64da-benchmark-toolkit/s64da_benchmark_toolkit/prepare.py", line 136, in run
    self.prepare_db()
  File "/home/nethomes/spiros/s64-benchmark-toolkit-git/s64da-benchmark-toolkit/s64da_benchmark_toolkit/prepare.py", line 184, in prepare_db
    self._load_schema(conn)
  File "/home/nethomes/spiros/s64-benchmark-toolkit-git/s64da-benchmark-toolkit/s64da_benchmark_toolkit/prepare.py", line 170, in _load_schema
    conn.cursor.execute(schema_sql)
psycopg2.errors.SyntaxError: syntax error at or near "{"
LINE 14: {% set num_partitions = num_partitions|int %}
         ^

**Comment by jukoson** [comment]
Looking into this
